spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/news
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

market-aux:
  uri:
    base-uri: https://api.marketaux.com
    all: /v1/news/all
    similar: /news/similar
    uuid: /news/uuid
    entity: /entity/search
    type: /entity/type/list
    industry: /entity/industry/list
  token: PcPhOlstzaDu8RrT6CdF1nlMhkOHcfKEMzw6gUeU
  domains: marketwatch.com,cnn.com,bloomberg.com,gurufocus.com,nasdaq.com,etftrends.com

etf:
  fngu: AAPL,AMZN,BABA,BIDU,META,GOOGL,MSFT,NFLX,NVDA,TSLA

kakao:
  token:
    rest: 822a4e53b28bbdac877388e2efd17eb5
  api:
    message:
      default-me: https://kapi.kakao.com/v2/api/talk/memo/default/send
      custom-me: https://kapi.kakao.com/v2/api/talk/memo/send
      friends: https://kapi.kakao.com/v1/api/talk/friends/message/send
    token: https://kauth.kakao.com/oauth/authorize
  redirect-uri: http://127.0.0.1:8080/oauth
