spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/news
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

market-aux:
  uri:
    base-uri: https://api.marketaux.com
    all: /v1/news/all
    similar: /news/similar
    uuid: /news/uuid
    entity: /entity/search
    type: /entity/type/list
    industry: /entity/industry/list
  token: PcPhOlstzaDu8RrT6CdF1nlMhkOHcfKEMzw6gUeU
  domains: marketwatch.com,cnn.com,bloomberg.com,gurufocus.com,nasdaq.com,etftrends.com

etf:
  fngu: AAPL,AMZN,BABA,BIDU,META,GOOGL,MSFT,NFLX,NVDA,TSLA