spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/news
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
# spring session 설정
  session:
    store-type: redis
    redis:
      namespace: gen:session
  redis:
    host: localhost
    password:
    port: 6379
    ssl: false
    timeout: 60000
  data:
    redis:
      host: localhost
      port: 6379
# Gmail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: gunho3987@gmail.com
    password: iwod hbkj dojr udqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Kakao Oauth2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 822a4e53b28bbdac877388e2efd17eb5
            client-secret: iiBxfEYAMftpPzHy0G1rBJoWoVye7dj2
            redirect_uri: "{baseUrl}/oauth2/kakao"
            authorizationGrant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kauth.kakao.com/v2/user/me
            user-name-attribute: id
# JWT Secret key
jwt:
  secret: bWFya2V0UnNzX3NlY3JldEtleV9naGthbmdfdG95X3Byb2plY3Rfand0VG9rZW4=
  access-time: 1 # 1H
  refresh-time: 7 # 7D

market-aux:
  uri:
    base-uri: https://api.marketaux.com
    all: /v1/news/all
    similar: /news/similar
    uuid: /news/uuid
    entity: /entity/search
    type: /entity/type/list
    industry: /entity/industry/list
  token: PcPhOlstzaDu8RrT6CdF1nlMhkOHcfKEMzw6gUeU
  domains: marketwatch.com,cnn.com,bloomberg.com,gurufocus.com,nasdaq.com,etftrends.com

etf:
  fngu: AAPL,AMZN,BABA,BIDU,META,GOOGL,MSFT,NFLX,NVDA,TSLA

kakao:
  token:
    rest: 822a4e53b28bbdac877388e2efd17eb5
  api:
    message:
      default-me: https://kapi.kakao.com/v2/api/talk/memo/default/send
      custom-me: https://kapi.kakao.com/v2/api/talk/memo/send
      friends: https://kapi.kakao.com/v1/api/talk/friends/message/send
    auth: https://kauth.kakao.com/oauth/authorize
    token: https://kauth.kakao.com/oauth/token
  redirect-uri: http://localhost:8080/oauth

korea-invest:
  key:
    open: PSXjfjX4UNCeWS5dD3NOB6KngQeXOmokOtul
    secret: 4dhHIwSuuVV+jjs/G7y6h47CGWCWy49rK2zmMRnu12d/PTOIbB+03bw7HOWHwMUeNH4Wd7XPWv4gXrAUgivyrlMyQiKtEBrsoljAuX6kwaIhw9mZX+hyDyF9NeaeG/CVN8eewC3/7M+o85i3BB5cIA0KFfrQJ0jALiKp/LQrG1HBjc/X2Dg=